weaveworks/launcher

bootstrap/main.go
=> bootstrap: Remove cluster user confirmation

bootstrap/main.go
since that won't necessarily land them in a good place.
Fixes #92
=> don't tell the user to go to WC

pkg/kubectl/kubectl.go
Unfortunately, we were looking for a string that has been introduced a bit later.
Fixes #99
=> agent: Fix the resource existence check on k8s 1.4

agent/main.go, bootstrap/main.go
Fixes https://github.com/weaveworks/launcher/issues/96
=> Add basic sentry error reporting to bootstrap

.circleci/config.yml, bootstrap/main.go, integration-tests/tests/flux-config.sh, integration-tests/tests/gke.sh, integration-tests/tests/install-update-flow.sh, integration-tests/tests/kube-system-migration.sh, pkg/gcloud/gcloud.go
=> bootstrap: Create clusterrolebinding for GKE

agent/main.go
Include `instanceID` in poll URL query parameters.
- This will be used for tracking agent adoption per instance.
- Track using `instanceID` instead of `token` so we can eventually remove token (secret) from GET requests.
=> agent: Include instanceID in poll URL query params

bootstrap/main.go, pkg/kubectl/kubectl.go
See https://sentry.io/weaveworks/launcher-bootstrap/issues/468318741/
Fixes #105
=> Send kubectl version info to sentry

agent/main.go
=> agent: Disable TLS checking

bootstrap/main.go
The related issue has the details.
Fixes: #122
=> Revert the agent objects when failing

.circleci/config.yml, Makefile, pkg/sentry/sentry.go, pkg/version/version.go
=> Add sentry release info to error reports

pkg/sentry/sentry.go
=> Fix sentry pkg init function not running

bootstrap/main.go, pkg/kubectl/kubectl.go
Fixes https://github.com/weaveworks/launcher/issues/134
=> Improve k8s version parsing, and user errors messages

pkg/kubectl/kubectl.go, pkg/kubectl/kubectl_test.go
https://weave-community.slack.com/archives/C2ND76PAA/p1521729481000068
=> Use full --output flag for kubectl 1.7 compatability

bootstrap/main.go
From https://weaveworks.slack.com/archives/C6NSJ9942/p1521727423000730
=> Make "kubectl version" instruction more actionable

.circleci/config.yml, pkg/kubectl/kubectl.go, pkg/kubectl/kubectl_test.go, pkg/kubectl/local_test.go
=> Fix --output usage

agent/main.go, bootstrap/main.go, service/static/agent.yaml.in, service/static/install.sh
=>  Disable error reports when testing locally 

.circleci/config.yml
Pushed tagged docker images to quay. Part of #170.
=> Push tagged versions to quay.io

agent/main_test.go
Not sure what happened there, I blame the weather.
=> cloudwatch: Make TestValidateResources actually run

agent/main.go
When we have an agent with a CRI endpoint specified, the auto-update has to
cary that state over. We do that by appending a GET parameter to the URL
generating the agent manifest.
An earlier attempt, changing the default agent poll URL didn't work because we
override that URL in the manifest served by service, removing the bit of
conditional templating that was added to the default parameter value.
Fixes: #256
=> agent: Fix agent poll URL with CRI endpoints

bootstrap/main.go
This reverts commit f2995f068e9e7e9d6c1d4b69b3d27a9075fd768a.
- If no `--cri-endpoint` flag is given, we'll look at the CRI runtime and guess the socket path for CRI-O and containerd.
- For docker, we don't use `--cri-endpoint`, so fallback to the current code
=> bootstrap: Re-enabled cri-endpoint flag"

.circleci/config.yml
Part of weaveworks/service-conf#3063.
=> Publish launcher-service to ECR

.circleci/config.yml
Counter is incremented on every run atm!
=> Only update failure metric when: on_fail

agent/flux.go, agent/main.go, agent/main_test.go
This commits adds support for having user defined memory (-m) and item
size (-I) configuration flags on their `weave-flux-memcached`
deployment.
This should provide users with enough knobs to work around
`SERVER_ERROR object too large for cache` errors due to exceptionally
large image repositories.
Fixes #284
=> Make Flux memcached args configurable

Gopkg.lock
Brings in many fixes over the last two years.
=> Update weaveworks/common to latest

.circleci/config.yml, integration-tests/tests/flux-config.sh, integration-tests/tests/install-update-flow.sh
I only had version 4 installed, so just upgrade the instructions.
=> build: Upgrade yq

.github/workflows/mirror-images.yaml
As the image may be accessed by either gitsha or release version
=> Add images for weave 2.8.1

.circleci/config.yml
This is being turned off, and I'm bored of emails it failed.
=> Remove health checks for latest k8s version
