weaveworks/launcher

- integration-tests/config.sh
- integration-tests/k8s/nginx-bootstrap.yaml.in
authfe uses 30081 already, move it elsewhere so we can run both.
> test: Install nginx-bootstrap in a different NodePort

- agent/main.go
- scripts/go-lint.sh
We don't do much with this today, might as well disable them.
Fixes: https://github.com/weaveworks/launcher/issues/84
> agent: Disable listening to kubernetes events

- agent/flux.go
- agent/main.go
- agent/migrate.go
- bootstrap/main.go
- pkg/kubectl/kubectl.go
- pkg/kubectl/local.go
- pkg/kubectl/local_test.go
- Use a kubectl client interface to allow us to reuse the logic when installing WC via other packages (e.g. remotely on GKE clusters).
- Make GlobalArgs a Client implementation detail to simplify interface and prevent misue of `Execute` vs `ExecuteWithGlobalArgs`
> Refactor kubectl pkg to use a client interface

- bootstrap/main.go
The comment should be self-explanatory and the issue has a longer discussion
about why this can happen.
Fixes: #120
> bootstrap: Don't error out if we can't display the cluster details

- bootstrap/main.go
Noticed when investigating an issue what we were missing a new line in the
warning message. An example of this can been seen in:
https://github.com/weaveworks/launcher/issues/117#issuecomment-368493059
> boostrap: Add missing new line in warning message

- bootstrap/main.go
When the final kubectl apply fails on GKE, we'd love to know why we weren't
able to create the cluster-admin role.
Based on that data, we can decide for a course of action to solve #117
Updates: #117
> bootstrap: Add the GKE clusterrolebinding error to the sentry context

- .circleci/config.yml
Ilya noticed that the dnsName parser has got more stringent.
https://github.com/golang/go/issues/23995
Stick with go 1.9 until that's addressed.
> ci: Use go 1.9

- agent/main.go
- bootstrap/main.go
- pkg/sentry/sentry.go
We noticed a few bad things:
- Agent events were all classified under one error because events with the same stack frame are aggregated together.
- Bootstrap events didn't have any stack frame associated with them.
- raven's Exception object prefixes error messages with the type of the `error`. The issue is that most errors we used are directly from `errors.New()` or indirectly from `fmt.Errorf()`. They have the same type: `*errors.errorString`. Sentry picked that up as the error name, which lead to having a walll of "errors.errorString" errors instead of more interesting messages.
- We weren't reporting some of the errors in agent when trying to talk to Kubernetes.
> Better error reporting

- agent/main.go
- bootstrap/main.go
- integration-tests/config.sh
- integration-tests/k8s/service.updated.yaml.in
- integration-tests/k8s/service.yaml.in
- pkg/kubectl/kubectl.go
- pkg/kubectl/kubectl_test.go
- pkg/weavecloud/instances.go
- pkg/weavecloud/instances_test.go
- service/main.go
- service/main_test.go
- service/static/agent.yaml.in
- service/static/install.sh
Also print the instance name when installing, and also if we do have to prompt.
Fixes https://github.com/weaveworks/launcher/issues/59
If the secret is missing or already matches:
```
Preparing for Weave Cloud setup
Checking kubectl & kubernetes versions
Connecting cluster to "" (id: thawing-fog-13) on Weave Cloud
Installing Weave Cloud agents on minikube at https://192.168.99.100:8443
Successfully installed.
```
If there is a secret:
```
Preparing for Weave Cloud setup
Checking kubectl & kubernetes versions
Connecting cluster to "" (id: thawing-fog-13) on Weave Cloud
Installing Weave Cloud agents on minikube at https://192.168.99.100:8443
This cluster is currently connected to "" (id: still-flower-11) on Weave Cloud
Would you like to continue and connect this cluster to "" (id: …
```
> Avoid prompting when overwriting secrets unless the instance ID differs 

- pkg/kubectl/kubectl.go
Ignore AlreadyExists errors so we don't show scary warnings to users.
Fixes #118
> make "create clusterrolebinding" idempotent

- .circleci/config.yml
Minikube v0.25.1 started causing tests to fail.
Issue: https://github.com/kubernetes/minikube/issues/2629
Lock the minikube version for now.
> Lock E2E test minikube version

- bootstrap/main.go
- pkg/kubectl/kubectl.go
- pkg/kubectl/kubectl_test.go
- pkg/kubectl/local.go
- pkg/kubectl/local_test.go
Adds a util to capture stderr separately to the combined output, so that we can make better error messages.
> Improve errors from running kubectl

- pkg/kubectl/kubectl.go
- pkg/kubectl/kubectl_test.go
We were using struct to store client and server versions, but this was from the
time where we decoded some JSON output and used those structs to unmarshal
into.
Lili pointed out we can do things in a nicer way now that we don't parse JSON,
removing the usage of those structs entirely.
Still need to be a bit careful with the error management, in particular kubectl
version could return the client version but not the server version because it
couldn't contact the API servers.
> kubectl: Simplify parseOutputVersion

- bootstrap/main.go
- pkg/kubectl/kubectl.go
- scripts/go-lint.sh
Sometimes DNS is not configured correctly, but during the launcher
process, DNS is required to setup all the needed resources. This creates
a check by creating a pod where nslookup is performed.
Closes #158.
Tests were not running on the old PR, so this is more or less a duplicate of #164.
> Add DNS check to bootstrap

- Gopkg.lock
- bootstrap/main.go
- pkg/kubectl/kubectl_test.go
As agreed in https://github.com/weaveworks/launcher/issues/162 we want to support cluster of 1.6.0 and above.
Because semantic versioning is hard (when handling things like alpha versions, etc.) and can become complicated I didn't want to re-write an entire parser so I choose to use https://github.com/blang/semver.
Closes https://github.com/weaveworks/launcher/issues/162
Note:
I did some testing and I ran into some problems as described on slack when using v1.6.0:
```
There was an error applying the agent: Error from server (NotFound): the server could not find the requested resource
Full output:
Error from server (NotFound): the server could not find the requested resource
Rolling back cluster changes
```
Not sure if this is related to DNS, or something else but maybe we should explore …
> Validate minimum Kubernetes cluster version 1.6.0

- bootstrap/main.go
This is needed due to the reported problems with users kubernetes
clusters having unsigned certificates.
Closes https://github.com/weaveworks/launcher/issues/173
> Pass flag to always skip checking certs validity

- pkg/kubectl/kubectl.go
> Escape commas in kubectl apply URLs

- pkg/gcloud/gcloud.go
gcloud prints various informative messages to stderr, which breaks our output processing.
Fixes #177
> don't combine stdout & stderr in gcloud execution

- bootstrap/main.go
- service/static/install.sh
This also adds a reserved error code 111 to bootstrap, which is used to
exclude the errors, so we only send the only produced in the script
itself.
> Send all errors that occur in the install script

- bootstrap/main.go
- scripts/go-lint.sh
As agreed we want to show the user when the bootstrap errors out in the UI as well, we do this by adding a new event `onboarding_failed`. In the next PR I will add to send errors whenever bootstrap itself fails or anything in the install script.
After this is merged and before we ship to production, we need to add the event type `onboarding_failed` to production as well, as it's currently only on dev and local. Will do a PR for that as well.
> bootstrap: Whenever we error out we inform the user

- pkg/kubectl/kubectl.go
When the user aborts and the pod does not get delated, on retry the user
gets an already exists error. This creates a pod with a random name, to
prevent that from happening.
As a side note: not sure if we should maybe prefix the name of the pod to be something like: `dns-check-b18c2c3885c29700` instead of `launcher-pre-flight-b18c2c3885c29700`. Maybe that would be more useful to the user?
Fixes https://github.com/weaveworks/launcher/issues/182
> Generate random pod name for DNS check

- bootstrap/main.go
The minimum role needed to create clusterrolebinding is the
"containers.admin" role.
This is how the actual full error looks like:
```
Could not create clusterrolebinding. GKE role "containers.admin" required to create resources.
Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "lili" cannot create clusterrolebindings.rbac.authorization.k8s.io at the cluster scope: Required "container.clusterRoleBindings.create" permission.
Full output:
Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "lili" cannot create clusterrolebindings.rbac.authorization.k8s.io at the cluster scope: Required "container.clusterRoleBindings.create" permission.
```
Open to suggestions about if we should include the k8s errors, …
> Error out when user lacks GKE cluster permission

- .circleci/config.yml
CircleCI requires `filters` `tag` to execute jobs on tagged pushes. https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
Only run the `agent` job because we are tagging releases from master manually and we only need to push the image.
Allows https://github.com/weaveworks/launcher/pull/192 to run.
> Run agent build job for tag pushes

- Gopkg.lock
- Gopkg.toml
- agent/main.go
- kubernetes/agent-debug-events.yaml
- pkg/k8s/config.go
- pkg/k8s/events.go
I'd like to gather prometheus metrics on how many k8s events are fired in dev so we can decide how we'd store k8s events if we were to send them to weave cloud.
This PR does just that, with a bit of cleanup fixes here and there. Installing WC looks like:
```
launcher_events_total{involved_object="DaemonSet",reason="SuccessfulCreate",type="Normal"} 2
launcher_events_total{involved_object="Deployment",reason="ScalingReplicaSet",type="Normal"} 5
launcher_events_total{involved_object="Node",reason="FailedToStartNodeHealthcheck",type="Warning"} 1
launcher_events_total{involved_object="Pod",reason="Created",type="Normal"} 9
launcher_events_total{involved_object="Pod",reason="Pulled",type="Normal"} 9
launcher_events_total{involved_object="Pod",reason="SandboxChanged",type="Normal"} 1 …
```
> Expose prom metrics for k8s events

- agent/main.go
- kubernetes/agent-debug-events.yaml
We don't need a token when not installing anything on the cluster. Reflect that
in the argument parsing code.
More could be done if featureInstall is false, ie don't attempt migration steps
or contact WC at all, but given it's a debug only flag, may not worth the time!
> agent: Don't require a token when not installing agents

- .circleci/config.yml
Due to occasional errors with pre-flight DNS check in the launcher, we
want to add this sleep for now, as a way of giving k8s time to setup DNS
in the cluster.
https://github.com/weaveworks/launcher/issues/199
Still think we should come up with a better solution then sleeping, so maybe we shouldn't close the issue for now. Guess doing a preflight check so we avoid failing a preflight check is a bit meta? :)
> circleci: Wait for DNS to be ready

- pkg/kubectl/kubectl.go
We have seen in the wild a otherwise perfectly working k8s hit the 30s timeout
(it typically takes 3s in our dev cluster). When the check is skipped the rest
of the installation happens flowlessly.
Bump the timeout to 1m to leave more time for the test to run.
> bootstrap: Bump the DNS test timeout to 1m

- .circleci/config.yml
To easily debug our flaky tests we are adding k8s events and resource
output whenever a test fails.
Closes https://github.com/weaveworks/launcher/issues/203.
> circleci: Output cluster state on test failure

- .circleci/config.yml
Pin to 1.9.0 cluster and update kubectl and minikube releases we use.
> circleci: Bump up k8s cluster in tests

- .circleci/config.yml
- integration-tests/common.sh
We have tests that fail, waiting for hours. We should properly timeout instead!
@LiliC suggested to use the built-in circle timeout instead of changing the waiting logic.
Cicle 2.0 only has the no_output_timeout key though. To make it work, we remove the '.' we printed for each iteration of the wait loop.
An example of test failing the timeout (I set it to 2s in that case for testing purposes): https://circleci.com/gh/weaveworks/launcher/9448?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Fixes: #68
> build: Add timeouts to integration steps

- agent/main.go
- agent/main_test.go
In some cases the minor and major versions are not set, so when forming
the Cloudwatch URL we want to fallback to using the GitVersion.
Closes https://github.com/weaveworks/launcher/issues/218
> agent: add fallback to k8s GitVersion

- integration-tests/k8s/nginx-bootstrap.yaml.in
- integration-tests/k8s/service.updated.yaml.in
- integration-tests/k8s/service.yaml.in
We have some flaky tests that output:
Error from server (BadRequest):
error when creating "./integration-tests/tests/../k8s/service.yaml":
the API version in the data (apps/v1beta1) does not match the expected API
version (apps/v1)
We should try and use the canonical apiVersion for our test manifests, starting
with Deployments.
Fixes: #167
> ci: Change deployments apiVersion to apps/v1

- agent/main.go
I had two bugs in there:
- The template variable needs {{ }}, not { }
- , is interpreted by kubectl and needs to be URL encoded.
Yes, needs some e2e tests!
- https://github.com/weaveworks/launcher/issues/228
> agent: Fix cloudwatch-exporter URL for multiple resources

- agent/cloudwatch.go
- agent/cloudwatch_test.go
- agent/main.go
- agent/main_test.go
This just extracts into a separate cloudwatch.go file and also separates the tests as previously discussed with @dlespiau. And addresses minor logging comments that @marccarre left in the previous PR.
---
Not entirely certain how much we want to log, if at all the msgs about each time an event is triggered are those useful? Any suggestions welcome!
Feel like below is too much noise maybe:
```
time="2018-06-12T10:24:39Z" level=info msg="configmaps \"cloudwatch\" not found"
time="2018-06-12T10:25:38Z" level=info msg="Secret was created"
time="2018-06-12T10:25:38Z" level=info msg="configmaps \"cloudwatch\" not found"
time="2018-06-12T10:26:06Z" level=info msg="ConfigMap was created"
time="2018-06-12T10:26:06Z" level=error msg="cloudwatch: at least one AWS resource must be specified" …
```
> Small refactorings and leftover stuff from previous PR

- .circleci/config.yml
- Gopkg.lock
- Gopkg.toml
- integration-tests/e2e/cloudwatch_test.go
- integration-tests/e2e/main_test.go
- integration-tests/e2e/resources/cloudwatch-cm.yaml
- integration-tests/e2e/resources/cloudwatch-secret.yaml
- integration-tests/tests/e2e.sh
First step towards having all the e2e tests in go! 🎉 
Closes https://github.com/weaveworks/launcher/issues/228
Note: Decided to just add a creation test, as the deletion one took a really long time around 5-10 minutes to delete all the resources, not sure if the benefits are there for that?
> Add cloudwatch e2e tests

- .circleci/config.yml
We can also say this closes https://github.com/weaveworks/launcher/issues/199, as so far all the failure with DNS on launcher were strictly due to kube-dns not being ready.
> circle-ci: Wait for actual kube-dns pod to be ready

- Gopkg.lock
- Gopkg.toml
- integration-tests/e2e/main_test.go
Lili suggested this package should be named kube-test-harness to make the
intent clearer. Clearer sounds like something you'd want!
> vendor: Use the renamed kube-test-harness

- integration-tests/setup/reset-local-minikube.sh
- integration-tests/setup/setup-local-minikube.sh
- integration-tests/tests/flux-config.sh
- integration-tests/tests/install-update-flow.sh
- integration-tests/tests/kube-system-migration.sh
The output of '.' prevented the timeout to happen, instead we should
rely on the timeout we set in the circleci config.
> tests: Remove output so tests can timeout

- .circleci/config.yml
- pkg/kubectl/kubectl.go
We often see failures of DNS preflight check, but do not know the
details of the failures.
> Output logs on failed DNS check

- .circleci/config.yml
- agent/main.go
- bootstrap/main.go
- pkg/kubectl/kubectl.go
- service/main.go
- service/main_test.go
- service/static/agent.yaml.in
Opening early so @dlespiau can base his work on the endpoint.
**DO NOT MERGE** until the complimentary PR is done in the generator.
We detect the CRI via the nodes command, and parse the CRI name and match that with the endpoint. Currently there is not good way of detecting the docker shim endpoint, as the name is always docker, but the user can always override their runtime with the `--cri-endpoint` flag.
> Add cri endpoint detection

- agent/main.go
- bootstrap/main.go
After update, we always "lost" the information about `cri-endpoint`.
Closes: https://github.com/weaveworks/launcher/issues/256
> agent: Pass cri-endpoint to agent manifest file

- agent/main.go
- agent/main_test.go
I thought the library would do it for me, but no. The URL struct only has the `WawQuery` field and String() compute the URL string with that field.
To add a GET parameter we need to encode the RawQuery manually.
This time, I unit-tested it, that's the price to pay when not getting right the first time!
> agent: Correctly encode the new GET parameters

- agent/main.go
- bootstrap/main.go
- service/main.go
- service/static/agent.yaml.in
Users may want to disable scope controls as they allow creating shells in containers, including the privileged containers. Add an option to prevent that.
The flow is a bit intricate, but that's the same one we have the `cri-endpoint` parameter.
- give the `--read-only` option to the installer (script)
- script forward option to bootstrap binary
- bootstrap uses it to ask for the agent manifest to the service through a URL Get parameter
- service serves an agent manifest with the `read-only` option
- agent uses that option to both:
- auto-updates: agent query service for agent manifests
- scope installs: agent uses the `read-only` parameter of the launch-generator to get the corresponding scope manifest.
While what we really want is going to a CRD with the various weave cloud options as …
> Provide a read-only option to the installer

- agent/main.go
- pkg/weavecloud/instances.go
Resolves https://github.com/weaveworks/service/issues/2369.
Depends on https://github.com/weaveworks/service/pull/2403.
The cluster K8s version is being reported to Weave Cloud every time the (new) agent starts, so the updates will always be sent alongside agent updates.
> Report K8s version to WC users service

- .circleci/config.yml
Currently fails with:
```
sudo apt-get -y -qq install awscli
aws s3 cp build/bootstrap/ s3://weaveworks-launcher/bootstrap/${CIRCLE_SHA1}/ --recursive
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3.5/libpython3.5-minimal_3.5.3-1_amd64.deb  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3.5/python3.5-minimal_3.5.3-1_amd64.deb  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3.5/libpython3.5-stdlib_3.5.3-1_amd64.deb  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3.5/python3.5_3.5.3-1_amd64.deb  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/pool/main/l/lcms2/liblcms2-2_2.8-4_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get …
```
> ci: Run apt-get update before install

- .circleci/config.yml
The health check runs every hour, so if we have an alert something like
```
increase(launcher_e2e_test_failures_total[120m]) > 2
```
we will only alert on two successive failures.
Part of #149.
> Update failure metric on healthcheck failure

- Gopkg.lock
- Allows us to ignore extra, undefined args if we want to, which we do
want to for parsing fluxd's arg list out of a k8s manifest
> Upgrades pflag to 1.0.3

- README.md
- agent/flux.go
- agent/main.go
- agent/main_test.go
- integration-tests/tests/flux-config.sh
- integration-tests/tests/kube-system-migration.sh
- service/static/install.sh
This adds to the list of fluxd flags that the agent will recognise and include in launch-generator URLs.
Since there are now more than four, and they don't all appear together necessarily, I've changed how the URL is constructed.
Fixes #277. (And needs a compensating change in the service being polled for configs.)
> Expand on the recognised fluxd flags

- service/static/agent.yaml.in
The extensions API has been removed from Kubernetes 1.13+ and our installer fails on newer clusters
> Update deployment API version to apps/v1beta1

- pkg/kubectl/kubectl.go
- Works w/ the latests 1.14 k8s + minikube
Fixes https://github.com/weaveworks/launcher/issues/285
> Switch to alpine for dns lookup tests

- .circleci/config.yml
- First go, use even more yaml anchor helpers
Fixes #288
> Test multiple versions of k8s

- agent/flux.go
- agent/main_test.go
This prevents the launcher from duplicating `[]string` arguments in some edge case scenarios.
- Dedupe `[]string` Flux args before building query
- Get Flux args from deployment instead of pods
> Improve Flux argument parsing

- .circleci/config.yml
Fixes health checker running after 1.18 was released yesterday
Minikube 1.7.3 adds some conntrack stuff needed by 1.18 https://github.com/kubernetes/minikube/releases
> Try upgrading minikube for k8s 1.18

- pkg/kubectl/kubectl.go
- pkg/kubectl/kubectl_test.go
- pkg/kubectl/local.go
- pkg/kubectl/local_test.go
Fixes a data race occuring between two goroutines writing to the same
buffer via two multiwriters.
Fixes #308 and also weaveworks/eksctl issue #1876
> Data Race during write to a combined buffer

- .circleci/config.yml
I broke it last week when I was rotating keys and moving this to a context - I
only put it back to one o the worklow jobs that needed it.
> build: Add ECR context to stable_kubernetes_still_works

- integration-tests/common.sh
- integration-tests/setup/setup-local-minikube.sh
If minikube were to return something rubbish, curl would still try to connect to
it - and it might wait for a reply for quite some time. It might be better to
back off and try again, which is why I've added a maximum 1 second request time.
Also removing the pipe all output to /dev/null - it won't normally print
anything (it's in quiet mode) but if we *were* to do something horribly wrong,
I would like to see it.
> build: Add timeout to curl loops

- .circleci/config.yml
- integration-tests/k8s/k8s-kube-system.yaml.in
- service/static/agent.yaml.in
This does three things:
* Fix deprecation that made weave cloud impossible to install on latest stable k8s. This new API namespace should work for any version 1.8+.
* Swap the order of the merge key things - `integration_install_update_flow` inherits 1.9, `job_environment_vstable` is supposed ot override it with latest stable. The way it was specified before didn't work though - in any recent build you can see 1.9 being printed like this, if you expand the right step:
With this change, it seems to work. For now? Maybe it works sometimes depending on the version of the yaml parser circleci has? I'm a bit nervous about it, but it seems to work - I'll replace it again in a bit.
* Use newer minikube for stable, because the old one failed.
This makes the build more reliable. By which I mean, …
> Actually use the k8s version we want to, fix fallout to make stable work

- .circleci/config.yml
This should
* Work - kind doesn't necessarily create an image for patch releases
* Not take lots of time and resources to rebuild latest stable k8s all the time
* Perhaps give us a bit of notice about prerelease versions? Not sure, TBC.
> build: Grab latest kind image instead of latest k8s version

- .github/workflows/mirror-images.yaml
Users are getting rate limited by dockerhub by our systems polling for changes to required images. This copies those images to GHCR where we won't get rate limited.
> Copy images required by weave cloud

- .github/workflows/mirror-images.yaml
As 'main' is the name of the default branch, not master
> 'master'->'main' in github action

- service/main.go
This endpoint should not be publicly visible. We disable it here by
switching `RegisterInstrumentation` to false and then manually adding
the `/metrics` endpoint back in. The rest of the metrics configuration
is handled by the server library so we can ignore that for the time
being.
> Disable `/debug/pprof` endpoint on the service

- .circleci/config.yml
The latest version can no longer be provisioned with the old kind
release, so we need a newer one.
The oldest version of k8s that we were testing, 1.12, doesn't run any more, but it's utterly unsupported so meh.
> ci: Upgrade kind version used in tests, stop testing k8s 1.12
